version: '3.8'

services:
  db:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=wordpress
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    # Nota: El comando de autenticación nativa sigue siendo válido para MySQL 8 y WP
    command: '--default-authentication-plugin=mysql_native_password'

  wordpress:
    depends_on:
      - db
    # En lugar de usar la imagen directa, le decimos que construya usando nuestro Dockerfile
    build:
      context: .
      dockerfile: wordpress.Dockerfile
    restart: unless-stopped
    environment:
      - WORDPRESS_DB_HOST=db:3306
      - WORDPRESS_DB_USER=${MYSQL_USER}
      - WORDPRESS_DB_PASSWORD=${MYSQL_PASSWORD}
      - WORDPRESS_DB_NAME=wordpress
    ports:
      - "80"